<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use App\Traits\DatabaseSeederTrait;

class AreaDampakDetailPGSeeder extends Seeder
{
    use DatabaseSeederTrait;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Nonaktifkan FK checks sesuai driver
        $this->disableForeignKeyChecks();

        // Reset data berdasarkan driver (PostgreSQL mendapat perlakuan khusus)
        try {
            if (DB::connection()->getDriverName() === 'pgsql') {
                // Truncate dengan reset identity dan cascade untuk FK
                DB::statement('TRUNCATE TABLE area_dampak_details RESTART IDENTITY CASCADE');
            } else {
                // MySQL dan lainnya
                DB::table('area_dampak_details')->truncate();
            }
        } catch (\Exception $e) {
            // Fallback: delete dan reset sequence untuk PostgreSQL
            DB::table('area_dampak_details')->delete();
            if (DB::connection()->getDriverName() === 'pgsql') {
                try {
                    DB::statement("ALTER SEQUENCE area_dampak_details_id_seq RESTART WITH 1");
                } catch (\Exception $seqEx) {
                    // ignore
                }
            }
        }

        // Aktifkan FK checks kembali
        $this->enableForeignKeyChecks();

        // Baca SQL sumber
        $path = database_path('seeders/sql/area_dampak_detail_pg.sql');
        $sql  = File::get($path);

        if (DB::connection()->getDriverName() === 'pgsql') {
            // Untuk PostgreSQL, pastikan kita dapat menginsert ID eksplisit
            // dengan menonaktifkan identity sementara jika diperlukan
            try {
                DB::statement("ALTER TABLE area_dampak_details ALTER COLUMN id DROP IDENTITY IF EXISTS");
            } catch (\Exception $e) {
                // abaikan jika kolom bukan identity
            }

            // Eksekusi SQL
            DB::unprepared($sql);

            // Set sequence ke nilai maksimum id
            $maxId = DB::table('area_dampak_details')->max('id');
            if ($maxId) {
                DB::statement("SELECT setval('area_dampak_details_id_seq', {$maxId}, true)");
            }

            // Aktifkan kembali identity sebagai GENERATED BY DEFAULT
            try {
                DB::statement("ALTER TABLE area_dampak_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
            } catch (\Exception $e) {
                // abaikan jika sudah diatur
            }
        } else {
            // Non-PG: eksekusi langsung
            DB::unprepared($sql);
        }
    }
}