<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use App\Traits\DatabaseSeederTrait;

class ParameterCriteriaDetailsSeeder extends Seeder
{
    use DatabaseSeederTrait;
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Nonaktifkan foreign key checks
        $this->disableForeignKeyChecks();
        
        // Truncate tabel untuk menghapus data yang ada
        try {
            // Untuk PostgreSQL, coba gunakan TRUNCATE dengan RESTART IDENTITY CASCADE
            if (DB::connection()->getDriverName() === 'pgsql') {
                DB::statement('TRUNCATE TABLE parameter_criteria_details RESTART IDENTITY CASCADE');
            } else {
                DB::table('parameter_criteria_details')->truncate();
            }
        } catch (\Exception $e) {
            // Jika gagal truncate, gunakan DELETE sebagai fallback
            DB::table('parameter_criteria_details')->delete();
            
            // Reset sequence untuk PostgreSQL jika truncate gagal
            if (DB::connection()->getDriverName() === 'pgsql') {
                try {
                    DB::statement('ALTER SEQUENCE parameter_criteria_details_id_seq RESTART WITH 1');
                } catch (\Exception $seqEx) {
                    // Jika reset sequence gagal, lanjutkan saja
                }
            }
        }
        
        // Aktifkan kembali foreign key checks
        $this->enableForeignKeyChecks();

        // Baca file SQL dan gunakan DB::unprepared untuk mengeksekusi SQL langsung
        $path = database_path('seeders/sql/parameter_criteria_details.sql');
        $sql = File::get($path);
        
        // Untuk PostgreSQL, kita perlu memodifikasi SQL agar sesuai dengan format PostgreSQL
        if (DB::connection()->getDriverName() === 'pgsql') {
            // Ubah format SQL dari MySQL ke PostgreSQL
            // 1. Ganti backtick dengan double quote
            $sql = str_replace('`', '"', $sql);
            
            // 2. Nonaktifkan identity column sementara untuk memungkinkan insert dengan ID eksplisit
            DB::statement("ALTER TABLE parameter_criteria_details ALTER COLUMN id DROP IDENTITY IF EXISTS");
            
            try {
                // 3. Eksekusi SQL yang sudah dimodifikasi
                DB::unprepared($sql);
                
                // 4. Cari ID maksimum untuk mengatur sequence
                $maxId = DB::table('parameter_criteria_details')->max('id');
                if ($maxId) {
                    // Set sequence ke nilai maksimum + 1
                    DB::statement("SELECT setval('parameter_criteria_details_id_seq', $maxId, true)");
                }
                
                // 5. Aktifkan kembali identity column
                DB::statement("ALTER TABLE parameter_criteria_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
            } catch (\Exception $e) {
                // Jika terjadi error, tampilkan pesan error
                $this->command->error("Error inserting data: " . $e->getMessage());
            }
        } else {
            // Untuk MySQL, eksekusi SQL langsung
            DB::unprepared($sql);
        }
    }
}