<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use App\Traits\DatabaseSeederTrait;

class ParameterCriteriaDetailsSeeder extends Seeder
{
    use DatabaseSeederTrait;
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Nonaktifkan foreign key checks
        $this->disableForeignKeyChecks();
        
        // Truncate tabel untuk menghapus data yang ada
        DB::table('parameter_criteria_details')->truncate();
        
        // Aktifkan kembali foreign key checks
        $this->enableForeignKeyChecks();

        // Baca file SQL
        $path = database_path('seeders/sql/parameter_criteria_details.sql');
        $sql = File::get($path);
        
        // Ekstrak data INSERT dari file SQL
        preg_match_all("/\(([^\)]+)\)/", $sql, $matches);
        
        $data = [];
        foreach ($matches[1] as $match) {
            $values = explode(',', $match);
            
            // Pastikan ada 7 nilai (id, parameter_criteria_id, criteria, level, created_at, updated_at, deleted_at)
            if (count($values) >= 6) {
                $id = trim($values[0]);
                $parameter_criteria_id = trim($values[1]);
                $criteria = trim($values[2], " '");
                $level = trim($values[3]);
                $created_at = trim($values[4], " '");
                $updated_at = trim($values[5], " '");
                $deleted_at = count($values) > 6 ? (trim($values[6]) === 'NULL' ? null : trim($values[6], " '")) : null;
                
                $data[] = [
                    'id' => $id,
                    'parameter_criteria_id' => $parameter_criteria_id,
                    'criteria' => $criteria,
                    'level' => $level,
                    'created_at' => $created_at,
                    'updated_at' => $updated_at,
                    'deleted_at' => $deleted_at
                ];
            }
        }
        
        // Insert data ke database PostgreSQL dengan ID yang sudah ditentukan
        if (!empty($data)) {
            // Untuk PostgreSQL, kita perlu menonaktifkan identity column sementara
            if (DB::connection()->getDriverName() === 'pgsql') {
                DB::statement("ALTER TABLE parameter_criteria_details DISABLE TRIGGER ALL");
                DB::statement("ALTER TABLE parameter_criteria_details ALTER COLUMN id SET NOT NULL");
                DB::statement("ALTER TABLE parameter_criteria_details ALTER COLUMN id DROP IDENTITY IF EXISTS");
            }
            
            // Insert data dengan ID yang sudah ditentukan
            DB::table('parameter_criteria_details')->insert($data);
            
            // Untuk PostgreSQL, aktifkan kembali identity column
            if (DB::connection()->getDriverName() === 'pgsql') {
                // Cari ID maksimum
                $maxId = DB::table('parameter_criteria_details')->max('id');
                if ($maxId) {
                    // Set sequence ke nilai maksimum + 1
                    DB::statement("SELECT setval('parameter_criteria_details_id_seq', $maxId, true)");
                }
                DB::statement("ALTER TABLE parameter_criteria_details ALTER COLUMN id SET NOT NULL");
                DB::statement("ALTER TABLE parameter_criteria_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
                DB::statement("ALTER TABLE parameter_criteria_details ENABLE TRIGGER ALL");
            }
        }
    }
}