<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use App\Traits\DatabaseSeederTrait;

class ParameterCriteriasSeeder extends Seeder
{
    use DatabaseSeederTrait;
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Nonaktifkan foreign key checks
        $this->disableForeignKeyChecks();
        
        // Truncate tabel untuk menghapus data yang ada
        try {
            DB::table('parameter_criterias')->truncate();
        } catch (\Exception $e) {
            // Jika truncate gagal, gunakan delete sebagai fallback
            DB::table('parameter_criterias')->delete();
        }
        
        // Aktifkan kembali foreign key checks
        $this->enableForeignKeyChecks();

        // Baca file SQL
        $path = database_path('seeders/sql/parameter_criterias.sql');
        $sql = File::get($path);
        
        // Untuk PostgreSQL, kita perlu menggunakan pendekatan parsing
        if (DB::connection()->getDriverName() === 'pgsql') {
            try {
                // Nonaktifkan identity column sementara tanpa menggunakan DISABLE TRIGGER ALL
                DB::statement("ALTER TABLE parameter_criterias ALTER COLUMN id SET NOT NULL");
                DB::statement("ALTER TABLE parameter_criterias ALTER COLUMN id DROP IDENTITY IF EXISTS");
                
                // Gunakan pendekatan parsing untuk PostgreSQL karena masalah format datetime
                $this->parseAndInsertData($sql);
                
                // Cari ID maksimum
                $maxId = DB::table('parameter_criterias')->max('id');
                if ($maxId) {
                    // Set sequence ke nilai maksimum + 1
                    DB::statement("SELECT setval('parameter_criterias_id_seq', $maxId, true)");
                }
                
                // Aktifkan kembali identity column
                DB::statement("ALTER TABLE parameter_criterias ALTER COLUMN id SET NOT NULL");
                DB::statement("ALTER TABLE parameter_criterias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
            } catch (\Exception $e) {
                // Jika pendekatan di atas gagal, gunakan pendekatan alternatif dengan parsing SQL
                $this->parseAndInsertData($sql);
            }
        } else {
            // Untuk database lain (MySQL), gunakan DB::unprepared
            DB::unprepared($sql);
        }
    }
    
    /**
     * Parse SQL dan insert data secara manual
     */
    private function parseAndInsertData($sql)
    {
        // Ekstrak data INSERT dari file SQL
        preg_match_all("/\(([^\)]+)\)/", $sql, $matches);
        
        $data = [];
        foreach ($matches[1] as $match) {
            $values = explode(',', $match);
            
            // Pastikan ada 8 nilai (id, parameter_id, criteria_statement, min_score, max_score, created_at, updated_at, deleted_at)
            if (count($values) >= 7) {
                $id = trim($values[0]);
                $parameter_id = trim($values[1]);
                $criteria_statement = trim($values[2], " '");
                $min_score = trim($values[3]);
                $max_score = trim($values[4]);
                $created_at = trim($values[5], " '");
                $updated_at = trim($values[6], " '");
                $deleted_at = count($values) > 7 ? (trim($values[7]) === 'NULL' ? null : trim($values[7], " '")) : null;
                
                $data[] = [
                    'id' => $id,
                    'parameter_id' => $parameter_id,
                    'criteria_statement' => $criteria_statement,
                    'min_score' => $min_score,
                    'max_score' => $max_score,
                    'created_at' => $created_at,
                    'updated_at' => $updated_at,
                    'deleted_at' => $deleted_at
                ];
            }
        }
        
        // Insert data ke database
        if (!empty($data)) {
            // Insert data dalam batch untuk efisiensi
            foreach (array_chunk($data, 50) as $chunk) {
                DB::table('parameter_criterias')->insert($chunk);
            }
        }
    }
}